<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('GcrInstitutionCatalogCourses', 'doctrine');

/**
 * BaseGcrInstitutionCatalogCourses
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $institution_short_name
 * @property string $catalog_short_name
 * @property integer $courses_count
 * 
 * @method integer    getId()      Returns the current record's "id" value
 * @method string     getInstitutionShortName() Returns the current record's "institution_short_name" value
 * @method string     getCatalogShortName() Returns the current record's "catalog_short_name" value
 * @method string     getCoursesCount() Returns the current record's "courses_count" value
 * @method GcrInstitutionCatalogCourses setId()      Sets the current record's "id" value
 * @method GcrInstitutionCatalogCourses setInstitutionShortName() Sets the current record's "institution_short_name" value
 * @method GcrInstitutionCatalogCourses setCatalogShortName() Sets the current record's "catalog_short_name" value
 * @method GcrInstitutionCatalogCourses setCoursesCount() Sets the current record's "courses_count" value
 * 
 * @package    globalclassroom
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGcrInstitutionCatalogCourses extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('gcr_institution_catalog_courses');
        $this->hasColumn('id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => false,
             'unsigned' => false,
             'primary' => true,
             'sequence' => 'gcr_institution_catalog_courses_id',
             'length' => 8,
             ));
        $this->hasColumn('platform_short_name', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));			 
        $this->hasColumn('institution_short_name', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));
        $this->hasColumn('catalog_short_name', 'string', null, array(
             'type' => 'string',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => false,
             'default' => '',
             'primary' => false,
             'length' => '',
             ));			 
        $this->hasColumn('courses_count', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 8,
             ));
        $this->hasColumn('product_type_id', 'integer', 8, array(
             'type' => 'integer',
             'fixed' => false,
             'unsigned' => false,
             'notnull' => true,
             'default' => '0',
             'primary' => false,
             'length' => 8,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}